package com.byonchat.android.provider;

public class Country {

    public static final String[] title = new String[]
           {/*"india","brazil",
                   "espana",
                   "deutschland",
                   "mexico",
                   "italia",
                   "Aland",
                   "America Samoa",
                   "Andora",
                   "Angola",
                   "Anguilla",
                   "Antigua and Barbuda",
                   "Argentina",
                   "Aruba",
                   "Ascension Island",
                   "Austalia",
                   "Azerbaijan",
                   "Bahamas",
                   "Barbados",
                   "Belgium",
                   "Belize",
                   "Benin",
                   "Bermuda",
                   "Bolivia",
                   "Bosna I Hercegovina",
                   "Botswana",
                   "British Indian Ocean Territory",
                   "British Virgin Islands",
                   "Brunei",
                   "Burkina Faso",
                   "Burundi",
                   "Cap Verde",
                   "Cammeroon",
                   "Canada",
                   "Caribbean Netherlands",
                   "Cayman Island",
                   "Czech Republic",
                   "Chile",
                   "Chistmas Island",
                   "Vatican City",
                   "Colombia",
                   "Congo-Brazzaville",
                   "Congo-Kinshasa",
                   "Cook Island",
                   "Costa Rica",
                   "Cote d'Ivoire",
                   "Cuba",
                   "Curacao",
                   "Denmark",
                   "Djibouti",
                   "Dominica",
                   "Ecuador",
                   "Estonia",
                   "El Salvador",
                   "Eretria",
                   "Falkland Island",
                   "Fiji",
                   "Faroe Island",
                   "France",
                   "Gabon",
                   "Gambia",
                   "Ghana",
                   "Gibraltar",
                   "Grenada",
                   "Guadeloupe",
                   "Guam",
                   "Guatemala",
                   "Guernsey",
                   "Guinea-Bissau",
                   "Equatorial Guinea",
                   "Guinea",
                   "Guyana",
                   "French Guiana",
                   "Haiti",
                   "Honduras",
                   "Croatia",
                   "South Africa",*/
                   "Indonesia"/*,
                   "Ireland",
                   "Iceland",
                   "Isle of Man",
                   "Jamaica",
                   "Jersey",
                   "Greenland",
                   "Kenya",
                   "Cocos (Keeling) Islands",
                   "Kiribati",
                   "Reunion",
                   "Latvia",
                   "Lesotho",
                   "Liberia",
                   "Liechtenstein",
                   "Lihuania",
                   "Lexemburg",
                   "Madagascar",
                   "Hungary",
                   "Malawi",
                   "Malaysia",
                   "Maldives",
                   "Mali",
                   "Malta",
                   "Marshall Islands",
                   "Martinique",
                   "Mauritius",
                   "Mayotte",
                   "Micronesia",
                   "Mozambique",
                   "Monaco",
                   "Montserrat",
                   "Namibia",
                   "Nauru",
                   "Netherland",
                   "New Zealand",
                   "Nicaragua",
                   "Niger",
                   "Nigeria",
                   "Niue",
                   "Norfolk Island",
                   "Norge",
                   "Northern Mariana Island",
                   "New Caledonia",
                   "Uzbekistan",
                   "Austria",
                   "Palau",
                   "Panama",
                   "Papua New Guinea",
                   "Paraguay",
                   "Peru",
                   "Philippines",
                   "Poland",
                   "French Polynesia",
                   "Portugal",
                   "Puerto Rico",
                   "Dominican Republic",
                   "Moldova",
                   "Central African Republic",
                   "Romania",
                   "Rwanda",
                   "Saint Helena",
                   "Saint Kitts and Nevis",
                   "Saint Lucia",
                   "Saint Barthelemy",
                   "Saint Martin",
                   "Saint Pierre and Miquelon",
                   "Samoa",
                   "San Marino",
                   "Sao Tome and Principe",
                   "Switzerland",
                   "Senegal",
                   "Seychelles",
                   "Albania",
                   "Sierra Leone",
                   "Singapore",
                   "Sint Maarten",
                   "Slovenia",
                   "Slovakia",
                   "Solomon Island",
                   "Somalia",
                   "South Sudan",
                   "St. Vincent & Grenadies",
                   "Finland",
                   "Suriname",
                   "Sverige",
                   "Swaziland",
                   "Tanzania",
                   "Chad",
                   "Timor-Leste",
                   "Togo",
                   "Tokelau",
                   "Tonga",
                   "Trinidad and Tobago",
                   "Turkey",
                   "Turks and Caicos Island",
                   "Tuvalu",
                   "U.S. Virgin Island",
                   "Uganda",
                   "United Kingdom",
                   "United States",
                   "Uruguay",
                   "Vanuatu",
                   "Venezuela",
                   "Vietnam",
                   "Wallis and Futuna",
                   "Zambia",
                   "Zimbabwe",
                   "Greece",
                   "Cyprus",
                   "Belarus",
                   "Bulgaria",
                   "Kyrgyzstan",
                   "Kazakhstan",
                   "Macedonia",
                   "Mongolia",
                   "Russia",
                   "Serbia",
                   "Tajikistan",
                   "Turkmenistan",
                   "Ukraine",
                   "Montenegro",
                   "Svalbard and jen Mayen",
                   "Georgia",
                   "Armenia",
                   "Israel",
                   "Afghanistan",
                   "Palestinian Territories",
                   "Jordan",
                   "United Arab Emirates",
                   "Bahrain",
                   "Algeria",
                   "Sudan",
                   "Iraq",
                   "Kuwait",
                   "Morocco",
                   "Saudi Arabia",
                   "Yemen",
                   "Pakistan",
                   "Tunisia",
                   "Comoros",
                   "Syria",
                   "Oman",
                   "Qatar",
                   "Lebanon",
                   "Libya",
                   "Egypt",
                   "Mauritania",
                   "Ethiopia",
                   "Nepal",
                   "Bangladesh",
                   "Sri Lanka",
                   "Thailand",
                   "Laos",
                   "Bhutan",
                   "Myanmar",
                   "Cambodia",
                   "South Korea",
                   "North Korea",
                   "China",
                   "Macau SAR China",
                   "Hong Kong SAR China",
                   "Taiwan",
                   "Japan",*/
           };

    public static final String[] code = new String[]
            {"62"
            /*"+91",
                    "+55",
                    "+34",
                    "+49",
                    "+52",
                    "+39",
                    "+358",
                    "+1",
                    "+376",
                    "+244",
                    "+1",
                    "+1",
                    "+54",
                    "+297",
                    "+247",
                    "+61",
                    "+994",
                    "+1",
                    "+1",
                    "+32",
                    "+501",
                    "+229",
                    "+1",
                    "+591",
                    "+387",
                    "+267",
                    "+246",
                    "+1",
                    "+673",
                    "+226",
                    "+257",
                    "+238",
                    "+237",
                    "+1",
                    "+599",
                    "+1",
                    "+420",
                    "+56",
                    "+61",
                    "+379",
                    "+57",
                    "+242",
                    "+243",
                    "+682",
                    "+506",
                    "+225",
                    "+53",
                    "+599",
                    "+45",
                    "+253",
                    "+1",
                    "+593",
                    "+372",
                    "+503",
                    "+291",
                    "+500",
                    "+679",
                    "+298",
                    "+33",
                    "+241",
                    "+220",
                    "+233",
                    "+350",
                    "+1",
                    "+590",
                    "+1",
                    "+502",
                    "+44",
                    "+245",
                    "+240",
                    "+224",
                    "+592",
                    "+594",
                    "+509",
                    "+504",
                    "+385",
                    "+27",
                    "+62",
                    "+543",
                    "+354",
                    "+44",
                    "+1",
                    "+44",
                    "+299",
                    "+254",
                    "+61",
                    "+686",
                    "+262",
                    "+371",
                    "+266",
                    "+231",
                    "+423",
                    "+370",
                    "+352",
                    "+261",
                    "+36",
                    "+265",
                    "+60",
                    "+960",
                    "+223",
                    "+356",
                    "+692",
                    "+596",
                    "+230",
                    "+262",
                    "+691",
                    "+258",
                    "+377",
                    "+1",
                    "+264",
                    "+674",
                    "+31",
                    "+64",
                    "+505",
                    "+227",
                    "+234",
                    "+683",
                    "+672",
                    "+47",
                    "+1",
                    "+687",
                    "+998",
                    "+43",
                    "+680",
                    "+507",
                    "+675",
                    "+595",
                    "+51",
                    "+63",
                    "+48",
                    "+689",
                    "+351",
                    "+1",
                    "+1",
                    "+373",
                    "+236",
                    "+40",
                    "+250",
                    "+290",
                    "+1",
                    "+1",
                    "+590",
                    "+590",
                    "+508",
                    "+685",
                    "+378",
                    "+239",
                    "+41",
                    "+221",
                    "+248",
                    "+355",
                    "+232",
                    "+65",
                    "+1",
                    "+386",
                    "+421",
                    "+677",
                    "+252",
                    "+211",
                    "+1",
                    "+358",
                    "+597",
                    "+46",
                    "+268",
                    "+255",
                    "+235",
                    "+670",
                    "+228",
                    "+690",
                    "+676",
                    "+1",
                    "+90",
                    "+1",
                    "+688",
                    "+1",
                    "+256",
                    "+44",
                    "+1",
                    "+598",
                    "+678",
                    "+58",
                    "+84",
                    "+681",
                    "+260",
                    "+263",
                    "+30",
                    "+357",
                    "+375",
                    "+359",
                    "+996",
                    "+7",
                    "+389",
                    "+976",
                    "+7",
                    "+381",
                    "+992",
                    "+993",
                    "+380",
                    "+382",
                    "+47",
                    "+995",
                    "+374",
                    "+972",
                    "+93",
                    "+970",
                    "+962",
                    "+971",
                    "+973",
                    "+213",
                    "+249",
                    "+964",
                    "+965",
                    "+212",
                    "+966",
                    "+967",
                    "+92",
                    "+216",
                    "+269",
                    "+963",
                    "+968",
                    "+974",
                    "+961",
                    "+218",
                    "+20",
                    "+222",
                    "+251",
                    "+977",
                    "+880",
                    "+94",
                    "+66",
                    "+856",
                    "+975",
                    "+95",
                    "+855",
                    "+82",
                    "+850",
                    "+86",
                    "+853",
                    "+852",
                    "+886",
                    "+81",*/
            };
    String nameContry;
    String codeContry ;

    public Country(String nameContry, String codeContry) {
        this.nameContry = nameContry;
        this.codeContry = codeContry;
    }

    public String getNameContry() {
        return nameContry;
    }

    public void setNameContry(String nameContry) {
        this.nameContry = nameContry;
    }

    public String getCodeContry() {
        return codeContry;
    }

    public void setCodeContry(String codeContry) {
        this.codeContry = codeContry;
    }
}
